const $=s=>document.querySelector(s);
const root=document.documentElement,stage=$('#stage'),phone=$('#phone'),angle=$('#angle');
let opening=155,playing=false,tilting=false,floating=false,lang='en',material='spectrum',drag=null,lastTime=0,raf=0,animation=0;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const copy={en:{concept:'AN INDEPENDENT CONCEPT',eyebrow:'THE HOLOGRAPHIC FOLD EXPERIMENT',headline:'A little fold.<br>A whole new <em>dimension.</em>',subtitle:'A phone. A collectible. A different kind of light.<br>Open it up and see what unfolds.',live:'LIVE MATERIAL',dragHint:'Drag to fold. Discover every angle.',angle:'OPENING ANGLE',finish:'01 — CHOOSE YOUR FINISH',reactive:'REACTS TO YOUR TOUCH',interaction:'02 — MAKE IT YOURS',spectrum:'Spectrum',aurora:'Aurora',chrome:'Liquid chrome',tilt:'Tilt & shine',float:'Float the card',note1:'Light that follows you.',desc1:'Every angle reveals a new spectrum.',note2:'Two screens. One canvas.',desc2:'A continuous artwork, split by a fold.',note3:'Made to be played.',desc3:'Touch, drag, and get a little curious.',footer:'A STUDY IN LIGHT & POSSIBILITY',credit:'Interaction inspiration: DOOD ↗',disclaimer:'Concept experience. Not an Apple product.'},zh:{concept:'独立交互概念设计',eyebrow:'镭射光影 · 折叠实验室',headline:'轻轻一折。<br>打开光的<em>另一面。</em>',subtitle:'一部手机，一张藏品，一种全新的光。<br>展开屏幕，让惊喜发生。',live:'实时光影材质',dragHint:'左右拖动折叠，发现每一个角度。',angle:'展开角度',finish:'01 — 选择镭射材质',reactive:'光泽随指尖变化',interaction:'02 — 玩出不同',spectrum:'全息光谱',aurora:'极光幻彩',chrome:'液态银铬',tilt:'转动追光',float:'卡片悬浮',note1:'光，跟随你的动作。',desc1:'每一次转动，都有新的色彩。',note2:'两面屏幕，一幅画。',desc2:'连续的镭射画面，在折叠处相遇。',note3:'为好奇心而设计。',desc3:'触摸、拖动，探索更多可能。',footer:'关于光与可能性的实验',credit:'交互灵感：DOOD ↗',disclaimer:'概念体验，非 Apple 官方产品。'}};
const finishes={spectrum:'linear-gradient(125deg,#faf6c1 0%,#cdfdca 16%,#77f2e6 29%,#a2a2f4 42%,#f29dcc 57%,#ffe6bb 72%,#edffaa 86%,#99f2e5 100%)',aurora:'linear-gradient(135deg,#8cfac6,#7fded1 22%,#a3bffa 42%,#cfabf0 62%,#a0eacb 82%,#8bf1e1)',chrome:'linear-gradient(125deg,#f9ffff,#a6b1bc 18%,#eef7fa 35%,#858e9b 48%,#e9f2f7 65%,#bdc7d2 80%,#f8ffff)'};
function update(){opening=Math.max(0,Math.min(180,opening));angle.value=Math.round(opening);$('#angleValue').textContent=Math.round(opening)+'°';root.style.setProperty('--fold',(180-opening)+'deg');root.style.setProperty('--phase',((180-opening)*.22)+'deg');root.style.setProperty('--mx',(30+opening*.2)+'%');const folded=opening<90;$('#fold').innerHTML=(lang==='zh'?(folded?'展开手机':'折叠手机'):(folded?'Unfold phone':'Fold phone'))+' <span>↗</span>';angle.setAttribute('aria-valuetext',Math.round(opening)+(lang==='zh'?' 度':' degrees'));}
function stop(){playing=false;cancelAnimationFrame(raf);cancelAnimationFrame(animation);$('#auto').textContent='▷';$('#auto').setAttribute('aria-pressed','false');$('#auto').setAttribute('aria-label',lang==='zh'?'自动开合':'Play automatic folding');}
function animateTo(target){stop();const from=opening,start=performance.now();if(reduced){opening=target;update();return;}function tick(now){const t=Math.min(1,(now-start)/850);opening=from+(target-from)*(1-Math.pow(1-t,3));update();if(t<1)animation=requestAnimationFrame(tick);}animation=requestAnimationFrame(tick);}
angle.addEventListener('input',()=>{stop();opening=Number(angle.value);update();});$('#fold').onclick=()=>animateTo(opening<90?180:0);
$('#auto').onclick=()=>{if(playing){stop();return;}stop();playing=true;$('#auto').textContent='Ⅱ';$('#auto').setAttribute('aria-pressed','true');$('#auto').setAttribute('aria-label',lang==='zh'?'暂停自动开合':'Pause automatic folding');lastTime=performance.now();const start=opening;function tick(now){opening=90+90*Math.sin((now-lastTime)/2300+Math.asin((start-90)/90));update();if(playing)raf=requestAnimationFrame(tick);}raf=requestAnimationFrame(tick);};
stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;stop();stage.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,angle:opening,moved:false};});
stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;if(!tilting){opening=drag.angle+dx*.65;update();}}if(tilting){root.style.setProperty('--ry',(-13+(x-.5)*55)+'deg');root.style.setProperty('--rx',(-9-(y-.5)*35)+'deg');}root.style.setProperty('--mx',(x*75+10)+'%');root.style.setProperty('--my',(y*80+10)+'%');root.style.setProperty('--phase',((x-.5)*50+(180-opening)*.22)+'deg');});
stage.addEventListener('pointerup',()=>{if(drag&&!drag.moved&&!tilting)animateTo(opening<90?180:0);drag=null;});stage.addEventListener('pointercancel',()=>drag=null);stage.addEventListener('lostpointercapture',()=>drag=null);
stage.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End',' '].includes(e.key)){e.preventDefault();stop();if(e.key===' ')animateTo(opening<90?180:0);else{opening=e.key==='Home'?0:e.key==='End'?180:opening+(e.key==='ArrowRight'?5:-5);update();}}});
function setMaterial(value){material=value;root.style.setProperty('--foil',finishes[value]);document.querySelectorAll('[data-material]').forEach(b=>{const active=b.dataset.material===value;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});$('#materialLabel').textContent=({spectrum:'01 / SPECTRUM',aurora:'02 / AURORA',chrome:'03 / LIQUID CHROME'})[value];}
document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>setMaterial(b.dataset.material));
function hint(){$('#gestureHint').textContent=tilting?(lang==='zh'?'在模型区域移动或拖动，转动手机追光。':'Move or drag across the phone to tilt & shine.'):copy[lang].dragHint;stage.style.cursor=tilting?'grab':'ew-resize';stage.style.touchAction=tilting?'none':'pan-y';}
$('#tilt').onclick=()=>{tilting=!tilting;$('#tilt').setAttribute('aria-pressed',String(tilting));if(!tilting){root.style.setProperty('--rx','-9deg');root.style.setProperty('--ry','-13deg');}hint();};
$('#float').onclick=()=>{floating=!floating;phone.classList.toggle('floating',floating);$('#float').setAttribute('aria-pressed',String(floating));if(floating&&opening<120)animateTo(155);};
$('#reset').onclick=()=>{stop();opening=155;tilting=floating=false;phone.classList.remove('floating');$('#tilt').setAttribute('aria-pressed','false');$('#float').setAttribute('aria-pressed','false');root.style.setProperty('--rx','-9deg');root.style.setProperty('--ry','-13deg');root.style.setProperty('--my','42%');setMaterial('spectrum');hint();update();};
$('#theme').onclick=()=>{const light=document.body.classList.toggle('light');$('#theme').setAttribute('aria-pressed',String(light));};
$('#language').onclick=()=>{lang=lang==='en'?'zh':'en';root.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-i]').forEach(el=>{if(copy[lang][el.dataset.i])el.innerHTML=copy[lang][el.dataset.i];});$('#language').textContent=lang==='en'?'中文':'EN';$('#language').setAttribute('aria-label',lang==='en'?'Switch to Chinese':'切换为英文');$('#theme').setAttribute('aria-label',lang==='zh'?'切换明暗主题':'Toggle light theme');$('#reset').setAttribute('aria-label',lang==='zh'?'重置全部控制':'Reset all controls');stage.setAttribute('aria-label',lang==='zh'?'手机模型，左右拖动或使用方向键调整折叠角度。':'Phone model. Drag to fold. Use arrow keys to change fold angle.');angle.setAttribute('aria-label',lang==='zh'?'展开角度':'Opening angle');$('#auto').setAttribute('aria-label',lang==='zh'?(playing?'暂停自动开合':'自动开合'):(playing?'Pause automatic folding':'Play automatic folding'));hint();update();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});update();
